### ISSUE TITLE
请问XCJGG里有已经封装好的计算表情键盘的方法吗？见下图

### ISSUE THREAD

**Issue by ZTing590** [cgmsuccess/XCJGG#1]
如下图，我想根据控制器view的高度减去表情键盘高度算出textview的高度。请问XCJGG里有已经封装好的计算表情键盘的方法吗？
![snip20180314_1](https://user-images.githubusercontent.com/17960472/37389265-9b6eb0e0-279e-11e8-88e9-16b31b09a762.png)

**Comment by cgmsuccess** [comment]
![default](https://user-images.githubusercontent.com/20773358/37389547-bc3a3df2-279f-11e8-9640-b37903d1cfe1.png)
这里是定义键盘的高度的宏 -- 》 XCEmotionDefine  里面可以修改键盘高度，
XC_EmojikeyBoardView 这个类是表情键盘管理类，里面装的是这几种不同的表情，表情键盘是公用的，是单例。默认高度是216 。
XC_EmotionsView  XC_EmotionInputView 这两个类我是写好的UI, 表情键盘的高度也是在这里面进行设置的。逻辑也在这2个类里面，
你如果不想用这2个类，想自定义的话，可以单例创建 XC_EmojikeyBoardView 他就是表情键盘，核心也在这里，然和设置 UITextview.inputView =  XC_EmotionInputView 就是表情键盘了

**Comment by ZTing590** [comment]
@cgmsuccess 明白了，谢谢🙏

**Comment by cgmsuccess** [comment]
客气😁
